### ISSUE TITLE
Feature Request: Option to enable live reload 

### ISSUE THREAD

**Issue by Ancient123** [tiangolo/uvicorn-gunicorn-docker#1]
gunicorn has the `--reload` option ( http://docs.gunicorn.org/en/19.0/settings.html#reload ) which helps with developing in the docker environment without constant rebuilds.

I tested it by adding `--reload` to the startup script manually but it would probably make sense to use a environment variable flag to enable/disable this.

**Comment by tiangolo** [comment]
Yep, there's a new integrated script in the image `/start-reload.sh`, it starts Uvicorn alone with live reload, which is optimal for development.

Check the new docs here: https://github.com/tiangolo/uvicorn-gunicorn-docker#development-live-reload

Let me know if it works for you.

**Comment by chbndrhnns** [comment]
Should we maybe also use the `reload_dirs` option here to reduce CPU load?

**Comment by tiangolo** [comment]
I don't think that's needed @chbndrhnns . This is only for quick development iterations, but for production that shouldn't be used at all.

**Comment by chbndrhnns** [comment]
I am aware that reload on change is not for production. However, when I develop on my laptop on battery, I noticed a huge difference when using ---reload-dirs compared to --reload.

I usually want a reload only on changes in my app directory but with --reload, uvicorn also looks in .venv/, for example. This leads to a high CPU load which matters to me when developing on battery. 

This is why I prefer [--reload-dir](https://www.uvicorn.org/settings/#development)

**Comment by tiangolo** [comment]
Get it, I think you could add it as a custom script for your use case @chbndrhnns , for example, you could add your own `/app/start-reload.sh` based on the one here, and run that one with all your customizations.

But I wouldn't add it as a default as other people will probably have different workflows.

---

@Ancient123 if your question was solved, then you can close this issue :rocket:
