### ISSUE TITLE
Image is not running

### ISSUE THREAD

**Issue by renedlog** [tiangolo/uvicorn-gunicorn-docker#11]
Im using the **python3.7-alpine3.8** folder to build the container
```
docker build -t myimage ./
docker run --name mycontainer -p 80:80 myimage
```
**': No such file or director**

**Comment by renedlog** [comment]
Closed: Git converted the ".sh" files with windows **CR LF line ending**. **Changing them to Linux LF** with notepad++ solved the issue

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
