### ISSUE TITLE
Allow to disable access logs

### ISSUE THREAD

**Issue by victornoel** [tiangolo/uvicorn-gunicorn-docker#14]
It would be great to document and/or add the possibility to disable access logs on top of setting the log level.

My use case is that the api is deployed behind a proxy that already is responsible for logging the access logs, so it is redundant for me to have it here.

**Comment by mr-bjerre** [comment]
+1

**Comment by mr-bjerre** [comment]
@victornoel did you find a solution to this? I am getting info logs from `uvicorn.access` although I have `LOG_LEVEL` set to `warning` in `gunicorn`.

**Comment by victornoel** [comment]
@mr-bjerre I ended up configuring a ini config file with this inside (I omitted the other things in it):
```
    [logger_gunicorn]
    level=INFO
    handlers=console
    propagate=0
    qualname=gunicorn

    [logger_gunicorn_access]
    level=WARNING
    handlers=console
    propagate=0
    qualname=gunicorn.access
```

And I pass it to gunicorn via `--log-config` (it means I run gunicorn by hand). I suppose #21 would be helpflu there.

**Comment by tiangolo** [comment]
You can now set (or disable) the access log with: https://github.com/tiangolo/uvicorn-gunicorn-docker#access_log :tada: 

And you can also pass Gunicorn configs in an env var: https://github.com/tiangolo/uvicorn-gunicorn-docker#gunicorn_cmd_args

**Comment by joshzana** [comment]
It looks like this works when running gunicorn in start.sh, but is ignored in start-reload.sh.  Would be great to get that script to run `exec uvicorn --reload --no-access-log` when `ACCESS_LOG` is unset.

**Comment by tiangolo** [comment]
@joshzana `start-reload.sh` is exclusively for local development, just as a simple, small, shortcut. You shouldn't use it for production. It will only use a single process and will use a lot more resources (memory, etc) watching files, etc.

But anyway, if for some reason you still need custom logic during development, you can also write a small script using `start-reload.sh` as template, and running that.

**Comment by cjmcgraw** [comment]
This problem persists for me.

I currently have the following gunicorn_conf.py set in my /app/gunicorn_conf.py:

``` python
# Gunicorn config variables
loglevel = "info"
workers = 2
threads = 8
bind = "0.0.0.0:80"

preload_app = False
statsd_host = "statsd:8125"
statsd_prefix = "recsys"
timeout = 180
keepalive = 120
accesslog = None
errorlog = "-"
```

While changing the accesslog parameter to stdout ("-") has gunicorn log. Uvicorn still is logging no matter what I do:

```
INFO:uvicorn.access:127.0.0.1:36678 - "GET /health/test HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46740 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46744 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46748 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46752 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46756 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46760 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46764 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46768 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46772 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46776 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46780 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46784 - "GET / HTTP/1.1" 200
INFO:uvicorn.access:172.17.0.1:46788 - "GET / HTTP/1.1" 200
```

Using the ACCESS_LOG parameter (or manually setting it in my gunicorn_conf.py) seems to have absolutely no effect on that log printing out.

I have yet to follow the advice of @victornoel and change out the logging configuration. I am wondering if we have a more direct and clear solution to this problem.

**Comment by cjmcgraw** [comment]
Following up on my previous post. If I clear out uvicorns access logger and turn off its propagation it seems to work.

```
import logging as log
app = ...
...

log.getLogger('uvicorn.access').handlers = []
log.getLogger('uvicorn.access').propagate = False
```

**Comment by tiangolo** [comment]
If anyone is still having issues, please try with a recent version of Uvicorn, a previous version was overriding the root logger.
