### ISSUE TITLE
Image for ARM64 chips

### ISSUE THREAD

**Issue by airatk** [tiangolo/uvicorn-gunicorn-docker#149]
Is there going to be implementation of support of chips with ARM64 architecture?

**Comment by tiangolo** [comment]
Is there a particular use case this would solve for you?

There's a high chance you don't even really need this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image

**Comment by airatk** [comment]
It would be much more efficient to use ARM-optimised image on ARM-based devices and servers, such as [AWS EC2 A1](https://aws.amazon.com/ec2/instance-types/a1/).

**Comment by tiangolo** [comment]
And wouldn't that be managed by Kubernetes or something like that? Wouldn't it still make sense to build a   local image directly?

Or why do you think it would be beneficial to use this same Docker image in those cases?
