### ISSUE TITLE
consider adding a python3-slim version

### ISSUE THREAD

**Issue by marcosfede** [tiangolo/uvicorn-gunicorn-docker#16]
Hi there, is adding a slim version something you'd consider? Using alpine has some nuances when adding numpy/pandas dependencies as explained [here](https://github.com/docker-library/python/issues/381)
Thanks

**Comment by laurentS** [comment]
I've just opened a PR that fixes this. Until it's merged, you can pull the image from https://hub.docker.com/r/laurents/uvicorn-gunicorn :)

**Comment by mattyweb** [comment]
I noticed that there was never actually a 3.7 slim image added for this...just a 3.8 slim. Any reason for that? Can one be added? Happy to jump in myself. I've got a few things that won't work on 3.8.

**Comment by tiangolo** [comment]
Thanks all for the comments! I released some time ago Python 3.8 and 3.9 slim, I hope you were able to update to those.

As Python 3.7 currently already reached end of life (https://devguide.python.org/versions/), I won't support it here, in fact, 3.8 is about to reach end of life as well. I hope you can migrate to a newer version of Python soon if you haven't! :nerd_face:
