### ISSUE TITLE
add a :latest-alpine tag

### ISSUE THREAD

**Issue by derekn** [tiangolo/uvicorn-gunicorn-docker#22]
it would be nice to have a generic :latest-alpine or simply :alpine tag to pull the latest version of python/alpine without using the verbose :python3.7-alpine3.8 tag

**Comment by tiangolo** [comment]
Yeah, the problem is that if the `latest` gets updated and you rebuild your image it could break as it is expecting a previous version.

It would also add even more maintenance burden, while it's easy to use the specific tag from the available ones.
