### ISSUE TITLE
Django ASGI: How to serve static files with this image

### ISSUE THREAD

**Issue by dwjorgeb** [tiangolo/uvicorn-gunicorn-docker#23]
What is the best way to serve static files while using this image for handling HTTP requests for Django ASGI?

**Comment by fribor** [comment]
Hi Jorge, I serve static files for Django with whitenoise. Just follow this [instructions ](http://whitenoise.evans.io/en/stable/django.html#) and add the following to your prestart.sh:

`python manage.py collectstatic --noinput`

Best,
Friedrich

**Comment by dwjorgeb** [comment]
> 
> 
> Hi Jorge, I serve static files for Django with whitenoise. Just follow this [instructions ](http://whitenoise.evans.io/en/stable/django.html#) and add the following to your prestart.sh:
> 
> `python manage.py collectstatic --noinput`
> 
> Best,
> Friedrich

Thank you! That worked for static files, but apparently does not work for media files. However, since my system does not rely on many media files, I'll probably use S3 or something like that.

**Comment by tiangolo** [comment]
Thanks for the help here @fribor !

If that solves your problem, may we close this issue? @dwjorgeb
