### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by gdoteof** [tiangolo/uvicorn-gunicorn-docker#3]
Is there a recommended way to serve these requests over HTTPS?

**Comment by gdoteof** [comment]
I was able to make this work by making my own gunicorn config file (just copying the one in the repo and adding the ssl options).  In the end a reverse proxy seemed even better.

**Comment by tiangolo** [comment]
Sorry for the delay, I'm glad you solved your problem.

Let me suggest Traefik as a reverse proxy.

You can use a project generator like: https://github.com/tiangolo/full-stack-fastapi-postgresql

And deploy it in a cluster with the ideas from https://dockerswarm.rocks/

**Comment by Mazyod** [comment]
As this issue is aptly called “SSL?”, it might be worth mentioning for other developers passing by the documentation of passing SSL configuration to gunicorn through environment variables:

https://github.com/tiangolo/uvicorn-gunicorn-docker#gunicorn_cmd_args
