### ISSUE TITLE
How to edit prestart.sh?

### ISSUE THREAD

**Issue by timpal0l** [tiangolo/uvicorn-gunicorn-docker#42]
I appreciate that a lot of parameters are set for you, but how can I manually edit them? I would rather not have a massive line of `-e` flags in my `docker run` command.

Such as: 

```
{
    "loglevel": loglevel,
    "workers": workers,
    "bind": bind,
    "graceful_timeout": graceful_timeout,
    "timeout": timeout,
    "keepalive": keepalive,
    "errorlog": errorlog,
    "accesslog": accesslog,
    # Additional, non-gunicorn variables
    "workers_per_core": workers_per_core,
    "use_max_workers": use_max_workers,
    "host": host,
    "port": port,
}
```

**Comment by autoferrit** [comment]
In your own dockerfile, you can add your own `prestart.sh` to the image with `COPY prestart.sh /app/prestart.sh` and you can set the path it looks for that with the ENV variable `PRE_STARTPATH=path/relative/to/workdir/prestart.sh`

**Comment by tiangolo** [comment]
Thanks for the help here @autoferrit ! :clap: :bow: 

If that solves the original problem, then you can close this issue @timpal0l  :heavy_check_mark:
