### ISSUE TITLE
multiprocessing.cpu_count() gives incorrect number of available cores when used within a docker container

### ISSUE THREAD

**Issue by KaneRodriguez** [tiangolo/uvicorn-gunicorn-docker#43]
As discussed [here](https://github.com/benoitc/gunicorn/issues/2028):
> If your container has been allocated (say) a single core and 512 MB of RAM on a machine with 64 cores, multiprocessing.cpu_count() thinks it has 64 cores instead of just 1, and you end up spawning 129 workers. This is way more than the container has resources for, and ends up causing out of memory crashes.

I ran into this issue with too many workers being spawned in a docker container on kubernetes, and my application would be in a constant CrashLoopBackoff state.

### Debug logs
```
{"loglevel": "info", "workers": 64, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
```

### Docker Image
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
```

### Relevant Line of Code 
https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/622470ec9aedb5da2cd2235bbca3f9e8e6256cdb/docker-images/gunicorn_conf.py#L21

### Solution
I've modified the default `gunicorn_config.py` to assign `cores` to an optional `AVAILABLE_CORES` variable; This is set when I define the number of cpus for the container.

```
cores = os.getenv("AVAILABLE_CORES", multiprocessing.cpu_count())
```

**Comment by tiangolo** [comment]
Great! I think you solved your problem, right?

If that's correct, then you can close this issue :heavy_check_mark:
