### ISSUE TITLE
PID 1 zombie reaping

### ISSUE THREAD

**Issue by xinbinhuang** [tiangolo/uvicorn-gunicorn-docker#48]
Hi,

I think this is more a gunicorn problem here. Currently, gunicorn is running as PID 1 in the Docker image, and my question is I wonder if gunicorn will reap out orphaned child processes?

Thanks 
Bin

**Comment by vstoykov** [comment]
Based on this post it looks like gunicorn will correctly handle the situation
http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html

**Comment by tiangolo** [comment]
Thanks for the help @vstoykov! 🍰 

If that answers your question, you can close the issue @xinbinhuang ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
