### ISSUE TITLE
Adding --env-file to uvicorn development script

### ISSUE THREAD

**Issue by ekundayo-ab** [tiangolo/uvicorn-gunicorn-docker#51]
Hi,

Please consider adding environment file path to the configurable env vars
```
# uvicorn-gunicorn-docker/docker-images/start-reload.sh
...
...
...
# Start Uvicorn with live reload
exec uvicorn --reload --host $HOST......... --env-file $PATH_TO_THE_ENV_FILE
```

Thanks

**Comment by tiangolo** [comment]
Thanks for the suggestion, but as this image uses Gunicorn to start the Uvicorn workers, that CLi option is not available.

But you probably don't really need this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image ...in that case, you could build your own using that CLI option.

As it's not possible to support that here, I'll close this issue. But thanks for the interest! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
