### ISSUE TITLE
About section :)

### ISSUE THREAD

**Issue by JulianVolodia** [tiangolo/uvicorn-gunicorn-docker#57]
Pretty sure there should be Python 3 not 3.6

> Docker image with Uvicorn managed by Gunicorn for high-performance web applications in Python 3.6 with performance auto-tuning. Optionally with Alpine Linux.

Cheers!

**Comment by graue70** [comment]
To clarify: This is about the 'About' section of the github repository. It is NOT about the `README.md` file.

**Comment by tiangolo** [comment]
Thanks! I updated it recently to just say Python, as the only versions supported by Python itself are 3.7 and above. :nerd_face: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
