### ISSUE TITLE
How to use "tiangolo/uvicorn-gunicorn-fastapi" under "conda" environment, and at the same time the command is "/bin/bash"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [tiangolo/uvicorn-gunicorn-docker#58]
Hi,
    I used “FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7” in the Dockerfile, however the command I got after docker running is "/start.sh". Due to my need is to call "tiangolo/fastapi" using "FROM continuumio/miniconda3", whether can I let the two different "FROM ..." ("FROM continuumio/miniconda3" and “FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7”) be combined in the same Dcokerfile?
Could you pls give me some suggestions?
    Note: My Dockerfile is below:
![1](https://user-images.githubusercontent.com/72843232/103963642-c78f5080-5194-11eb-926a-8f5fe4883f2c.png)
Moreover, the results of executing "docker ps" while using "FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7":
![2](https://user-images.githubusercontent.com/72843232/103963711-edb4f080-5194-11eb-91e6-9c5480e707fa.png)
Another result of executing "docker ps" while using "FROM continuumio/miniconda3":
![3](https://user-images.githubusercontent.com/72843232/103963869-2e146e80-5195-11eb-8027-23b6ce5517eb.png)

**Comment by StashOfCode** [comment]
Hi! Any updates on this?

**Comment by tiangolo** [comment]
By using another `FROM` directive you are no longer using this image. Docker doesn't have a way to mix the base layers of two Docker images.

In this case, you would have to do the work manually. But there's a chance that you don't really need this Docker image at all: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
