### ISSUE TITLE
The pinned versions on docker hub still use uvicorn without uvloop

### ISSUE THREAD

**Issue by kkpattern** [tiangolo/uvicorn-gunicorn-docker#59]
Only the [latest](https://hub.docker.com/layers/tiangolo/uvicorn-gunicorn-fastapi/latest/images/sha256-b166262843a61ef1079d76fca023cfba34d65569203013269749b519e0fcb4e1?context=explore) tag has the uvicorn installed with uvloop.

The pinned version like [uvicorn-gunicorn-fastapi:python3.8-2020-12-19](https://hub.docker.com/layers/tiangolo/uvicorn-gunicorn-fastapi/python3.8-2020-12-19/images/sha256-dc7ccd01872231254a04b82011180608a1f80d455674e1b302aa719b7c02065b?context=explore) still use `/bin/sh -c pip install --no-cache-dir uvicorn gunicorn` instead of `/bin/sh -c pip install --no-cache-dir "uvicorn[standard]" gunicorn`.

**Comment by tiangolo** [comment]
Yep, precisely, the pinned versions are what was there at that exact point in time, the whole idea is that those versions are not changed, and if you run something with them it will always run exactly like that.

If you need a new version, you should probably use a new, more recent pin.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by kkpattern** [comment]
yeah. I think back then what I really meant is that we need to create a new pinned version that uses uvloop. Sorry for not being clear. If there are already new pinned versions with uvloop I think we can close this issue.

**Comment by tiangolo** [comment]
Great, thanks! ☕
