### ISSUE TITLE
Unix Socket Image available ?

### ISSUE THREAD

**Issue by eimfach** [tiangolo/uvicorn-gunicorn-docker#60]
Hey,

is there an image which works with unix sockets (I want to talk to my uvicorn container via nginx reverse proxy and socket) instead of TCP ?

**Comment by tiangolo** [comment]
Hmm, I don't think Docker works that way, I wouldn't know how to do it. 🤔 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
