### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by sylvainmouquet** [tiangolo/uvicorn-gunicorn-docker#73]
As a developer, i would like to get a docker image based on python 3.9

**Comment by hasanzabaak** [comment]
I've been using @rushilsrivastava's fork for the 3.9 images: https://github.com/rushilsrivastava/uvicorn-gunicorn-docker

**Comment by anton-petrov** [comment]
@sylvainmouquet 
You can use my fork https://hub.docker.com/repository/docker/antonapetrov/uvicorn-gunicorn
It's already tested and using in production.

**Comment by AntonOfTheWoods** [comment]
@anton-petrov on your docker hub page there are links to versions with `starlette` and `fastapi` but they seem to be broken. Was the intent to allow a drop-in replacement for the `fastapi` `postgres` template?

**Comment by anton-petrov** [comment]
@AntonOfTheWoods thanks a lot))) fixed. anyway, this is a temporary solution

**Comment by thomasleveil** [comment]
@sylvainmouquet this can now be closed
