### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by wshayes** [tiangolo/uvicorn-gunicorn-docker#8]
Was reading these recommendations https://pythonspeed.com/articles/gunicorn-in-docker/ and noticed that they were not integrated in the relevant Dockerfiles as defaults. 

* heartbeat file in /dev/shm --> --worker-tmp-dir /dev/shm
* Logging -> --log-files=-

**Comment by tiangolo** [comment]
Interesting!

So, the `--log-files` refers to this setting: http://docs.gunicorn.org/en/stable/settings.html#errorlog, which is set here: https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/python3.6/gunicorn_conf.py#L30 :heavy_check_mark: 

The `--worker-tmp-dir` refers to this: http://docs.gunicorn.org/en/stable/settings.html#worker-tmp-dir, it would be a line with `worker_tmp_dir = "/dev/shm"`, probably under the previous line. :grey_question: 

Would you like to add a PR with that?

**Comment by wshayes** [comment]
Sorry missed the log-files config. Just added the PR for the heartbeat file. Thanks!

**Comment by tiangolo** [comment]
Thanks for your help @wshayes ! It's merged now, so I'll close this issue. But feel free to add more comments, new issues, etc.

**Comment by mr-bjerre** [comment]
Any reason this was only implemented in python3.6 image and not the other images?

**Comment by tiangolo** [comment]
@mr-bjerre hmm, not sure what you refer to. :thinking: 

This is implemented in all the images, the links for Python 3.6 above are just an example of the location where it is located.

**Comment by mr-bjerre** [comment]
Are you sure? Looking at python 3.7 image it doesn't look like it to me!?

https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/python3.7/gunicorn_conf.py

**Comment by tiangolo** [comment]
@mr-bjerre I think you were right, I recently made a big refactor to make all the images share the same config and avoid the chance of having desynchronizations like that for each image :sweat_smile:
