### ISSUE TITLE
RuntimeError: Task attached to a different loop

### ISSUE THREAD

**Issue by mawoka-myblock** [tiangolo/uvicorn-gunicorn-docker#81]
Yea, Hello everyone! Today, I tried to put my program into production, and this happened:
`2021-08-17T14:35:18.959815442Z RuntimeError: Task <Task pending name='Task-7' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py:375> cb=[set.discard()]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.8/asyncio/futures.py:360]> attached to a different loop
`. Yea, I don't know how to fix it. The line which produces the problem: `if await col.find_one({"name": name}) is not None:` (Which works great with uvicorn outside of the container.)
Edit:
I am using motor (MongoDB)

**Comment by Margolp80** [comment]
Any luck yet?
I'm stuck with the same problem

**Comment by mawoka-myblock** [comment]
I defined the `col` outside of the async function, but it has to be in the function! You have to initialize the mongodb-thing inside the function which runs for a request
