### ISSUE TITLE
New uvicorn[standard] version cause memory leak due to tcp ping

### ISSUE THREAD

**Issue by KiraPC** [tiangolo/uvicorn-gunicorn-docker#98]
As I described in the uvicorn issue https://github.com/encode/uvicorn/issues/1226 using standard uvicorn version from 0.14.0 tcp ping cause memory leak that end with OOM.

Since this image use that version, it should be affected by the leak.

Someone faced this problem?

**Comment by nvtkaszpir** [comment]
I guess we see something similiar with kubernetes standard tcp probe where it just checks if port is open.
